// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package handler

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for ListTasksParamsIsDeleted.
const (
	ListTasksParamsIsDeletedFalse ListTasksParamsIsDeleted = "false"
	ListTasksParamsIsDeletedTrue  ListTasksParamsIsDeleted = "true"
)

// Valid indicates whether the value is a known member of the ListTasksParamsIsDeleted enum.
func (e ListTasksParamsIsDeleted) Valid() bool {
	switch e {
	case ListTasksParamsIsDeletedFalse:
		return true
	case ListTasksParamsIsDeletedTrue:
		return true
	default:
		return false
	}
}

// Defines values for ListTasksParamsIsCompleted.
const (
	ListTasksParamsIsCompletedFalse ListTasksParamsIsCompleted = "false"
	ListTasksParamsIsCompletedTrue  ListTasksParamsIsCompleted = "true"
)

// Valid indicates whether the value is a known member of the ListTasksParamsIsCompleted enum.
func (e ListTasksParamsIsCompleted) Valid() bool {
	switch e {
	case ListTasksParamsIsCompletedFalse:
		return true
	case ListTasksParamsIsCompletedTrue:
		return true
	default:
		return false
	}
}

// Defines values for ListTasksParamsInbox.
const (
	True ListTasksParamsInbox = "true"
)

// Valid indicates whether the value is a known member of the ListTasksParamsInbox enum.
func (e ListTasksParamsInbox) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// AddLabelRequest defines model for AddLabelRequest.
type AddLabelRequest struct {
	LabelId openapi_types.UUID `json:"label_id"`
}

// CreateLabelRequest defines model for CreateLabelRequest.
type CreateLabelRequest struct {
	Colour string `json:"colour"`
	Name   string `json:"name"`
}

// CreateListRequest defines model for CreateListRequest.
type CreateListRequest struct {
	Colour   string  `json:"colour"`
	Icon     *string `json:"icon,omitempty"`
	Name     string  `json:"name"`
	Position string  `json:"position"`
}

// CreateSubtaskRequest defines model for CreateSubtaskRequest.
type CreateSubtaskRequest struct {
	Position string `json:"position"`
	Title    string `json:"title"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Description *string `json:"description,omitempty"`

	// DueDate YYYY-MM-DD format
	DueDate *string `json:"due_date,omitempty"`

	// DueTime HH:MM 24-hour format
	DueTime  *string             `json:"due_time,omitempty"`
	ListId   *openapi_types.UUID `json:"list_id,omitempty"`
	Position string              `json:"position"`
	Priority int                 `json:"priority"`
	Title    string              `json:"title"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// IdResponse defines model for IdResponse.
type IdResponse struct {
	Id openapi_types.UUID `json:"id"`
}

// Label defines model for Label.
type Label struct {
	Colour    *string            `json:"colour,omitempty"`
	CreatedAt *time.Time         `json:"created_at,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
}

// List defines model for List.
type List struct {
	Colour    *string            `json:"colour,omitempty"`
	CreatedAt time.Time          `json:"created_at"`
	Icon      *string            `json:"icon,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Position  string             `json:"position"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// Subtask defines model for Subtask.
type Subtask struct {
	Id          openapi_types.UUID `json:"id"`
	IsCompleted bool               `json:"is_completed"`
	Position    string             `json:"position"`
	Title       string             `json:"title"`
}

// Task defines model for Task.
type Task struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	Description *string    `json:"description,omitempty"`

	// DueDate YYYY-MM-DD format
	DueDate *string `json:"due_date,omitempty"`

	// DueTime HH:MM 24-hour format
	DueTime        *string             `json:"due_time,omitempty"`
	Id             openapi_types.UUID  `json:"id"`
	IsCompleted    bool                `json:"is_completed"`
	IsDeleted      bool                `json:"is_deleted"`
	Labels         *[]Label            `json:"labels,omitempty"`
	ListId         *openapi_types.UUID `json:"list_id,omitempty"`
	Position       string              `json:"position"`
	Priority       int                 `json:"priority"`
	RecurrenceRule *string             `json:"recurrence_rule,omitempty"`
	Subtasks       *[]Subtask          `json:"subtasks,omitempty"`
	Title          string              `json:"title"`
	UpdatedAt      time.Time           `json:"updated_at"`
}

// UpdateSubtaskRequest defines model for UpdateSubtaskRequest.
type UpdateSubtaskRequest struct {
	Title string `json:"title"`
}

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	Description    *string             `json:"description,omitempty"`
	DueDate        *string             `json:"due_date,omitempty"`
	DueTime        *string             `json:"due_time,omitempty"`
	ListId         *openapi_types.UUID `json:"list_id,omitempty"`
	Position       *string             `json:"position,omitempty"`
	Priority       *int                `json:"priority,omitempty"`
	RecurrenceRule *string             `json:"recurrence_rule,omitempty"`
	Title          *string             `json:"title,omitempty"`
}

// ListId defines model for ListId.
type ListId = openapi_types.UUID

// SubtaskId defines model for SubtaskId.
type SubtaskId = openapi_types.UUID

// TaskId defines model for TaskId.
type TaskId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	IsDeleted   *ListTasksParamsIsDeleted   `form:"is_deleted,omitempty" json:"is_deleted,omitempty"`
	IsCompleted *ListTasksParamsIsCompleted `form:"is_completed,omitempty" json:"is_completed,omitempty"`
	ListId      *openapi_types.UUID         `form:"list_id,omitempty" json:"list_id,omitempty"`
	LabelId     *openapi_types.UUID         `form:"label_id,omitempty" json:"label_id,omitempty"`
	Inbox       *ListTasksParamsInbox       `form:"inbox,omitempty" json:"inbox,omitempty"`
}

// ListTasksParamsIsDeleted defines parameters for ListTasks.
type ListTasksParamsIsDeleted string

// ListTasksParamsIsCompleted defines parameters for ListTasks.
type ListTasksParamsIsCompleted string

// ListTasksParamsInbox defines parameters for ListTasks.
type ListTasksParamsInbox string

// CreateLabelJSONRequestBody defines body for CreateLabel for application/json ContentType.
type CreateLabelJSONRequestBody = CreateLabelRequest

// CreateListJSONRequestBody defines body for CreateList for application/json ContentType.
type CreateListJSONRequestBody = CreateListRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = UpdateTaskRequest

// AddLabelToTaskJSONRequestBody defines body for AddLabelToTask for application/json ContentType.
type AddLabelToTaskJSONRequestBody = AddLabelRequest

// CreateSubtaskJSONRequestBody defines body for CreateSubtask for application/json ContentType.
type CreateSubtaskJSONRequestBody = CreateSubtaskRequest

// UpdateSubtaskTitleJSONRequestBody defines body for UpdateSubtaskTitle for application/json ContentType.
type UpdateSubtaskTitleJSONRequestBody = UpdateSubtaskRequest
